version: "3"
services:
  gitlab:
    build: ./docker/gitlab
    container_name: gitlab
#    hostname: 'gitlab.hogehoge.hoge'
#    environment:
#      GITLAB_OMNIBUS_CONFIG: |
#        external_url 'https://gitlab.hogehoge.hoge'
    ports:
      - 80:80
    volumes:
      - ./docker/gitlab-data/config:/etc/gitlab
      - ./docker/gitlab-data/logs:/var/log/gitlab
      - ./docker/gitlab-data/data:/var/opt/gitlab

